[객체지향의 사실과 오해] Ch7, 부록 작성 완료
Booktionary/Booktionary pull request #22
Opened 2022-12-21 14:35 UTC by Seung72

2022-12-22 00:39 UTC, dh3183 requested changes
[🙋🏻‍♂️ 확인 요청]
1. 함께 모으기 : Review 참고 부탁드려요!
2. 부록 : 파일명을 '부록 A / 추상화 기법'으로 변경해 주세요!

2022-12-22 00:39 UTC, dh3183 commented on 02. 객체지향의 사실과 오해/함께 모으기.md
> +<img src="https://user-images.githubusercontent.com/79628706/208682959-8064cc8a-cc61-4f8c-a5e1-b9ed33f56c78.png" width="250px"/>
혹시 해당 이미지에 대한 비율(혹은 크기)을 조금 더 크게 가능한지 궁금해요. 조금 더 이미지의 크기가 크면 좋을 거 같아요!

2022-12-22 00:39 UTC, dh3183 commented on 02. 객체지향의 사실과 오해/함께 모으기.md
> +<img src="https://user-images.githubusercontent.com/79628706/208683332-9279873c-552a-4c3b-9388-f06ee0166861.png" width="350px"/>
이 부분도~

2022-12-22 00:39 UTC, dh3183 commented on 02. 객체지향의 사실과 오해/함께 모으기.md
> +소프트웨어는 항상 변하고 설계는 변경을 위해 존재한다. 소프트웨어 클래스가 도메인 개념을 따르면 변화에 쉽게 대응할 수 있다.
해당 부분과 같이 한 줄로 끝나면서 (~ 다.)로 끝나는 경우엔 불릿 포인트로 정리하는 건 어떨까 싶어요!

2022-12-22 00:57 UTC, dh3183 requested changes
이건 선택이니 참고하세요~ 👀

2022-12-22 00:57 UTC, dh3183 commented on 02. 객체지향의 사실과 오해/함께 모으기.md
> +<img src="https://user-images.githubusercontent.com/79628706/208682959-8064cc8a-cc61-4f8c-a5e1-b9ed33f56c78.png" width="250px"/>
혹시 해당 이미지에 대한 비율(혹은 크기)을 조금 더 크게 가능한지 궁금해요. 조금 더 이미지의 크기가 크면 좋을 거 같아요!

2022-12-22 00:57 UTC, dh3183 commented on 02. 객체지향의 사실과 오해/함께 모으기.md
> +<img src="https://user-images.githubusercontent.com/79628706/208683332-9279873c-552a-4c3b-9388-f06ee0166861.png" width="350px"/>
이 부분(이미지 크기)도 확인해주세요

2022-12-22 00:57 UTC, dh3183 commented on 02. 객체지향의 사실과 오해/함께 모으기.md
> +```
🙋🏻‍♂️[참고하세요!]
Backtick(```) 바로 오른쪽에 해당 코드의 언어를 적으면 해당 언어의 문법에 맞게 코드에 색깔이 입혀져서 가독성 좋게끔 하이라이팅 된 채로 보여줄 수 있어요 😏


예시 : 적용 전 
```
struct FixedLengthRange {
    var firstValue: Int
    let length: Int
}
var rangeOfThreeItems = FixedLengthRange(firstValue: 0, length: 3)

rangeOfThreeItems.firstValue = 6
```

예시 : 적용 후
```Swift
struct FixedLengthRange {
    var firstValue: Int
    let length: Int
}
var rangeOfThreeItems = FixedLengthRange(firstValue: 0, length: 3)

rangeOfThreeItems.firstValue = 6
```

2022-12-22 10:18 UTC, Seung72 commented on 02. 객체지향의 사실과 오해/함께 모으기.md
> +소프트웨어는 항상 변하고 설계는 변경을 위해 존재한다. 소프트웨어 클래스가 도메인 개념을 따르면 변화에 쉽게 대응할 수 있다.
[⭕ 요청 확인]

1.  Review 참고하여 수정하겠습니다.
2. '부록 A / 추상화 기법' 와 같이 파일명 수정 시, 새 Directory가 생성되기 때문에 '부록 A - 추상화 기법' 으로 수정하겠습니다.

2022-12-22 10:18 UTC, Seung72 commented on 02. 객체지향의 사실과 오해/함께 모으기.md
> +<img src="https://user-images.githubusercontent.com/79628706/208682959-8064cc8a-cc61-4f8c-a5e1-b9ed33f56c78.png" width="250px"/>
이미지 해상도 및 크기에 대해 수정하겠습니다.

2022-12-22 10:19 UTC, Seung72 commented on 02. 객체지향의 사실과 오해/함께 모으기.md
> +```
알려주셔서 감사합니다.

2022-12-22 10:28 UTC, Seung72 commented
요청사항 수정 후 재 PR 요청입니다.

2022-12-24 15:35 UTC, dh3183 approved these changes
수고하셨습니다 👍🏻👍🏻

2022-12-24 15:35 UTC, merged